### ISSUE TITLE
parsec.service fails to start on Fedora IoT 37/38

### ISSUE THREAD

**Issue by drlamb** [fedora-iot/dbus-parsec#12]
On both of my Fedora 38 IoT systems (x86_64 and aarch64) parsec.service fails to start. This issue was present in Fedora 37 as well.

```
May 26 10:36:03 hostname.example.com systemd[1]: parsec.service: Scheduled restart job, restart counter is at 4.
May 26 10:36:03 hostname.example.com systemd[1]: Stopped parsec.service - Parsec Service.
May 26 10:36:03 hostname.example.com systemd[1]: Starting parsec.service - Parsec Service...
May 26 10:36:03 hostname.example.com parsec[1268]: Error: Permission denied (os error 13)
May 26 10:36:03 hostname.example.com systemd[1]: parsec.service: Main process exited, code=exited, status=1/FAILURE
May 26 10:36:03 hostname.example.com systemd[1]: parsec.service: Failed with result 'exit-code'.
May 26 10:36:03 hostname.example.com systemd[1]: Failed to start parsec.service - Parsec Service.
```

Default state of `/var/lib/parsec`  :

```
[root@example parsec]# ls -al
total 0
drwxr-xr-x. 1 parsec  parsec          16 May  2 21:06 .
drwxr-xr-x. 1 root    root           836 May  8 15:21 ..
drwxr-xr-x. 1 dnsmasq parsec-clients   0 May  2 21:06 mappings

```

`chown -R parsec:parsec /var/lib/parsec` allows parsec.service to start

**Comment by pm4rcin** [comment]
@puiterwijk @nullr0ute @decathorpe sorry guys for pinging you but is something going to be done to fix that? Do we know what's causing that issue? Here's the same [issue](https://discussion.fedoraproject.org/t/parsec-service-failed-to-start/84135) that other people experience. It'd be nice to fix it before F39 comes out.

**Comment by drlamb** [comment]
Now on Fedora 39 I had to repeat the above and on x86_64 I additionally had to give `parsec` ownership of `/etc/parsec/` so that parsec could read `/etc/parsec/config.toml` and start. Following the upgrade `/etc/parsec/` was owned by clevis. 

```
ls -al /etc/parsec/
total 8
drwxr-x---. 1 clevis clevis   22 Nov  8 12:07 .
drwxr-xr-x. 1 root   root   3914 Nov  8 12:08 ..
-rw-r--r--. 1 root   root    479 May 11 01:34 config.toml
```

`chown parsec:parsec /etc/parsec/`

**Comment by pm4rcin** [comment]
@drlamb looks like it's [fixed](https://bugzilla.redhat.com/show_bug.cgi?id=2170957#c19) in F40. Issue could be closed I guess.

**Comment by nullr0ute** [comment]
Yes, it's fixed, I missed this variant of the bug report. I believe it's fixed in F-39 now too.
